# Generated by Django 2.2.26 on 2024-05-31 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(verbose_name='Valor de la compra')),
                ('cuotas', models.IntegerField(default=1, verbose_name='Número de cuotas')),
                ('info', models.TextField(max_length=300, verbose_name='Informacion')),
                ('deuda', models.IntegerField()),
                ('cancelada', models.BooleanField(default=False, verbose_name='Cancelada')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'CompraCredito',
                'verbose_name_plural': 'CompraCredito',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre de la Cuenta')),
                ('saldo', models.IntegerField(verbose_name='Saldo de cuenta')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Etiqueta')),
                ('tipo', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90, verbose_name='Nombre de la Persona')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('yopresto', 'Yo presto'), ('meprestan', 'Me prestan')], max_length=30, verbose_name='Tipo de prestamo')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('info', models.CharField(max_length=200, verbose_name='Informacion')),
                ('cancelada', models.BooleanField(default=False, verbose_name='Cancelada')),
                ('saldo_pendiente', models.IntegerField(verbose_name='Saldo pendiente')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Persona')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SubTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SubTag',
                'verbose_name_plural': 'SubTags',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=30, verbose_name='Tipo de transaccion')),
                ('saldo_anterior', models.IntegerField(verbose_name='Saldo anterior')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('info', models.TextField(max_length=300, verbose_name='Descripción')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('estado', models.IntegerField(default=1, verbose_name='Estado')),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta')),
                ('etiqueta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Etiqueta')),
                ('subtag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.SubTag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaccion',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionPrestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(default=2)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Prestamo')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Transaccion')),
            ],
            options={
                'verbose_name': 'TransaccionPrestamo',
                'verbose_name_plural': 'TransaccionPrestamo',
                'ordering': ['-transaccion__fecha'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionPagoCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compraCredito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.CompraCredito')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Transaccion')),
            ],
            options={
                'verbose_name': 'TransaccionPagoCredito',
                'verbose_name_plural': 'TransaccionPagoCredito',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudPagoPrestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagoMultiple', models.BooleanField(default=False)),
                ('valor', models.IntegerField(default=0)),
                ('info', models.CharField(default='', max_length=250)),
                ('fechaPago', models.CharField(blank=True, max_length=250, null=True)),
                ('pagoMultipleTipoPrestamo', models.CharField(blank=True, max_length=20, null=True)),
                ('fechaSolicitud', models.DateTimeField()),
                ('estado', models.IntegerField(default=0)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Persona')),
                ('prestamo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Prestamo')),
                ('usuarioAprueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_aprueba', to=settings.AUTH_USER_MODEL)),
                ('usuarioSolicita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_solicita', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fechaSolicitud'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCreacionPrestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('valor', models.IntegerField()),
                ('info', models.TextField()),
                ('fechaPrestamo', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaSolicitud', models.DateTimeField()),
                ('estado', models.IntegerField(default=0)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Persona')),
                ('usuarioAprueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAprueba', to=settings.AUTH_USER_MODEL)),
                ('usuarioSolicita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userSolicita', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fechaSolicitud'],
            },
        ),
        migrations.CreateModel(
            name='GrupoTransaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaccionHija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_hijas', to='contabilidad.Transaccion')),
                ('transaccionPadre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_padres', to='contabilidad.Transaccion')),
            ],
            options={
                'verbose_name': 'GrupoTransaccion',
                'verbose_name_plural': 'GrupoTransaccion',
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('cupo', models.IntegerField()),
                ('cupoDisponible', models.IntegerField(verbose_name='Cupo disponible')),
                ('diaCorte', models.IntegerField(verbose_name='Dia de corte')),
                ('diaPago', models.IntegerField(verbose_name='Dia de pago')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CreditCard',
                'verbose_name_plural': 'CreditCards',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CompraCreditoPrestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compraCredito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.CompraCredito')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Prestamo')),
            ],
            options={
                'verbose_name': 'CompraCreditoPrestamo',
                'verbose_name_plural': 'CompraCreditoPrestamo',
            },
        ),
        migrations.AddField(
            model_name='compracredito',
            name='creditCard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.CreditCard'),
        ),
        migrations.AddField(
            model_name='compracredito',
            name='etiqueta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Etiqueta'),
        ),
    ]
