# Generated by Django 2.2.26 on 2023-07-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_auto_20230529_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcard',
            options={'ordering': ['id'], 'verbose_name': 'Credit card', 'verbose_name_plural': 'Credit cards'},
        ),
        migrations.AddField(
            model_name='creditcard',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
        migrations.AddField(
            model_name='persona',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
    ]
