# Generated by Django 2.2.26 on 2023-08-25 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_auto_20230813_0024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtag',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cantidad',
            field=models.IntegerField(verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='info',
            field=models.TextField(max_length=300, verbose_name='Descripción'),
        ),
        migrations.CreateModel(
            name='GrupoTransaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaccionHija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_hijas', to='contabilidad.Transaccion')),
                ('transaccionPadre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_padres', to='contabilidad.Transaccion')),
            ],
        ),
    ]
