# Generated by Django 2.2.26 on 2023-11-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_auto_20230825_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupotransaccion',
            options={'verbose_name': 'Grupo transaccion', 'verbose_name_plural': 'Grupo transacciones'},
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
    ]
