# Generated by Django 2.2.26 on 2023-11-28 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_auto_20231120_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraCreditoPrestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compraCredito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.CompraCredito')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Prestamo')),
            ],
        ),
    ]
