# Generated by Django 2.2.26 on 2023-12-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_compracreditoprestamo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compracredito',
            options={'ordering': ['-fecha'], 'verbose_name': 'CompraCredito', 'verbose_name_plural': 'CompraCredito'},
        ),
        migrations.AlterModelOptions(
            name='compracreditoprestamo',
            options={'verbose_name': 'CompraCreditoPrestamo', 'verbose_name_plural': 'CompraCreditoPrestamo'},
        ),
        migrations.AlterModelOptions(
            name='creditcard',
            options={'ordering': ['id'], 'verbose_name': 'CreditCard', 'verbose_name_plural': 'CreditCards'},
        ),
        migrations.AlterModelOptions(
            name='grupotransaccion',
            options={'verbose_name': 'GrupoTransaccion', 'verbose_name_plural': 'GrupoTransaccion'},
        ),
        migrations.AlterModelOptions(
            name='subtag',
            options={'ordering': ['nombre'], 'verbose_name': 'SubTag', 'verbose_name_plural': 'SubTags'},
        ),
        migrations.AlterModelOptions(
            name='transaccionpagocredito',
            options={'ordering': ['id'], 'verbose_name': 'TransaccionPagoCredito', 'verbose_name_plural': 'TransaccionPagoCredito'},
        ),
        migrations.AlterModelOptions(
            name='transaccionprestamo',
            options={'ordering': ['-transaccion__fecha'], 'verbose_name': 'TransaccionPrestamo', 'verbose_name_plural': 'TransaccionPrestamo'},
        ),
        migrations.AddField(
            model_name='transaccionprestamo',
            name='tipo',
            field=models.IntegerField(default=2),
        ),
    ]
