# Generated by Django 2.2.26 on 2024-03-06 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0009_auto_20231202_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPagoPrestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagoMultiple', models.BooleanField(default=False)),
                ('valorPago', models.IntegerField()),
                ('info', models.CharField(blank=True, max_length=250, null=True)),
                ('fechaPago', models.CharField(blank=True, max_length=250, null=True)),
                ('tipoPrestamoPagoMultiple', models.CharField(blank=True, max_length=20, null=True)),
                ('fechaSolicitud', models.DateTimeField()),
                ('estado', models.IntegerField(default=0)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta')),
                ('prestamo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Prestamo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
