# Generated by Django 2.2.26 on 2024-03-13 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0010_solicitudpagoprestamo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCreacionPrestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('valor', models.IntegerField()),
                ('info', models.TextField()),
                ('fechaPrestamo', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaSolicitud', models.DateTimeField()),
                ('estado', models.IntegerField(default=0)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Persona')),
                ('usuarioAprueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAprueba', to=settings.AUTH_USER_MODEL)),
                ('usuarioSolicita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userSolicita', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fechaSolicitud'],
            },
        ),
    ]
