# Generated by Django 2.2.26 on 2024-05-28 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_solicitudcreacionprestamo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudpagoprestamo',
            name='pagoMultiplePersonaId',
        ),
        migrations.RemoveField(
            model_name='solicitudpagoprestamo',
            name='valorPago',
        ),
        migrations.AddField(
            model_name='solicitudpagoprestamo',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Persona'),
        ),
        migrations.AddField(
            model_name='solicitudpagoprestamo',
            name='valor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solicitudpagoprestamo',
            name='info',
            field=models.CharField(default='', max_length=250),
        ),
    ]
