# Generated by Django 2.2.26 on 2023-12-03 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersetting',
            options={'ordering': ['id'], 'verbose_name': 'UserSetting', 'verbose_name_plural': 'UserSettings'},
        ),
    ]
