# Generated by Django 2.2.26 on 2024-03-05 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_auto_20231202_2234'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0002_auto_20231202_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_admin', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Persona')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_persona', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
