# Generated by Django 2.2.26 on 2024-05-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_notificationlinkbutton_usernotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='linkButton',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='routeParam',
        ),
        migrations.AddField(
            model_name='usernotification',
            name='type',
            field=models.TextField(default=0),
        ),
        migrations.DeleteModel(
            name='NotificationLinkButton',
        ),
    ]
