# Generated by Django 2.2.26 on 2024-06-30 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pagador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apto.Apartamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorPago', models.IntegerField()),
                ('fechaInicio', models.CharField(max_length=100)),
                ('fechaFin', models.CharField(max_length=100)),
                ('diasFacturados', models.IntegerField()),
                ('apto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apto.Apartamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apto.Empresa')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apto.Periodo')),
            ],
            options={
                'ordering': ['-periodo'],
            },
        ),
        migrations.CreateModel(
            name='PersonaPagador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apto.Pagador')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoPrestamoPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apto.Periodo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Persona')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Prestamo')),
            ],
        ),
        migrations.CreateModel(
            name='PagadorRecibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorPago', models.IntegerField()),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apto.Pagador')),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apto.Recibo')),
            ],
        ),
        migrations.CreateModel(
            name='Estadia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.CharField(max_length=100)),
                ('fechaFin', models.CharField(max_length=100)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apto.PersonaPagador')),
            ],
        ),
    ]
