# Generated by Django 2.2.26 on 2024-07-02 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ['-nombre']},
        ),
        migrations.AlterModelOptions(
            name='recibo',
            options={'ordering': ['-periodo__nombre']},
        ),
    ]
