# Generated by Django 2.2.26 on 2024-06-01 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagador',
            name='nombre',
        ),
    ]
