# Generated by Django 2.2 on 2019-09-19 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'ordering': ['-fecha'], 'verbose_name': 'Prestamo', 'verbose_name_plural': 'Prestamos'},
        ),
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Transaccion', 'verbose_name_plural': 'Transacciones'},
        ),
    ]
