# Generated by Django 2.2.26 on 2023-05-17 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0002_transaccion_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(verbose_name='Valor de la compra')),
                ('cuotas', models.IntegerField(default=1, verbose_name='Número de cuotas')),
                ('info', models.TextField(max_length=300, verbose_name='Informacion')),
                ('cancelada', models.BooleanField(default=False, verbose_name='Cancelada')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Compra a credito',
                'verbose_name_plural': 'Compras a credito',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='persona',
            name='isCreditCard',
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='tipo',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='TransaccionPagoCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagoRealizado', models.BooleanField(default=False, verbose_name='Cancelada')),
                ('compraCredito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.CompraCredito')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Transaccion')),
            ],
            options={
                'verbose_name': 'Transacción pago credito',
                'verbose_name_plural': 'Transacciones pago credito',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('cupo', models.IntegerField()),
                ('cupoDisponible', models.IntegerField(verbose_name='Cupo disponible')),
                ('diaCorte', models.IntegerField(verbose_name='Dia de corte')),
                ('diaPago', models.IntegerField(verbose_name='Dia fecha limite de pago')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit card',
                'verbose_name_plural': 'Credit cards',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='compracredito',
            name='creditCard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.CreditCard'),
        ),
        migrations.AddField(
            model_name='compracredito',
            name='etiqueta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Etiqueta'),
        ),
    ]
