# Generated by Django 2.2.26 on 2023-05-05 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0002_transaccion_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('cupo', models.IntegerField()),
                ('cupoDisponible', models.IntegerField()),
                ('diaCorte', models.IntegerField(verbose_name='Dia fecha de corte')),
                ('diaLimitePago', models.IntegerField(verbose_name='Dia fecha limite de pago')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit card',
                'verbose_name_plural': 'Credit cards',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='persona',
            name='isCreditCard',
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='tipo',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='TransaccionCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuotas', models.IntegerField(default=1, verbose_name='Número de cuotas')),
                ('fechaLimitePago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha limite de pago')),
                ('creditCard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.CreditCard')),
                ('etiqueta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Etiqueta')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Transaccion')),
            ],
            options={
                'verbose_name': 'Transacción con credit card',
                'verbose_name_plural': 'Transacciones con credit card',
                'ordering': ['id'],
            },
        ),
    ]
